services:
  - type: web
    name: hip-camp
    env: python
    pythonVersion: 3.10.13
    buildCommand: |
      npm install --prefix react-app
      npm run build --prefix react-app
      pip install --upgrade pip
      pip install -r requirements.txt
      cp -r react-app/build/* app/static/
      flask db upgrade
      flask seed all
    startCommand: gunicorn app:app
    envVars:
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: SECRET_KEY
        value: your-secure-random-secret-key
